In [2]:
import numpy as np

In [4]:
arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr2[2,0]

7

In [7]:
arr2[:1,2:]

array([[3]])

In [9]:
arr2[:2,1:]

array([[2, 3],
       [5, 6]])

In [10]:
arr2[:0,2:]

array([], shape=(0, 1), dtype=int32)

In [11]:
arr2 > 3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
bool = arr2 > 5

In [13]:
bool

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [15]:
arr2[bool]

array([6, 7, 8, 9])

In [16]:
arr2[arr2 < 5]

array([1, 2, 3, 4])

In [17]:
arr3 = np.arange(60).reshape(6,10)

In [45]:
arr3

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [48]:
arr3.sum(axis = 0)

array([150, 156, 162, 168, 174, 180, 186, 192, 198, 204])

In [50]:
arr3.sum(axis = 1)

array([ 45, 145, 245, 345, 445, 545])

In [20]:
arr3[4:5,3:8]

array([[43, 44, 45, 46, 47]])

In [22]:
arr3[0:2,8:]

array([[ 8,  9],
       [18, 19]])

In [23]:
arr3[4:,8:]

array([[48, 49],
       [58, 59]])

In [26]:
#sclicing the array components

In [27]:
arr3[:3,5:]

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [25, 26, 27, 28, 29]])

In [28]:
arr3[2:4,0:]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [29]:
#Numpy operations
#array with array
#array with scalars
#Universal array functions

In [30]:
arr4 = np.arange(0,11)

In [31]:
arr4 + arr4

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [32]:
arr4 * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [33]:
arr4 * arr4

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [34]:
arr4 - 1

array([-1,  0,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [36]:
arr4 ** 4

array([    0,     1,    16,    81,   256,   625,  1296,  2401,  4096,
        6561, 10000], dtype=int32)

In [37]:
1 / arr4

<ipython-input-37-3d00e7c2d54d>:1: RuntimeWarning: divide by zero encountered in true_divide
  1 / arr4


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [38]:
#universal array function
np.sqrt(arr4)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [39]:
np.exp(arr4)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [40]:
np.max(arr4)

10

In [42]:
np.sin(arr4)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [43]:
np.log(arr4)

<ipython-input-43-8db28cd3c497>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr4)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [44]:
arr4.dtype

dtype('int32')