In [1]:
import numpy as np

In [5]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [6]:
# Number of brakets shows how many dimension the array is

In [8]:
prob = [[1,2,3],[4,5,6],[7,8,0]]
np.array(prob)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 0]])

In [9]:
# arange is similar to Range in Python
#arange([start,] stop[, step,], dtype=None, *, like=None)

In [10]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
#Giving step sizes:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [12]:
#to get a mtrices of one specific number
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [17]:
#  linspace gives evenly spaced numbers over a specied interval
#np.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None,axis=0,)
#The endpoint of the interval can optionally be excluded.
np.linspace(0,100,15)

array([  0.        ,   7.14285714,  14.28571429,  21.42857143,
        28.57142857,  35.71428571,  42.85714286,  50.        ,
        57.14285714,  64.28571429,  71.42857143,  78.57142857,
        85.71428571,  92.85714286, 100.        ])

In [18]:
# to create identity matrix. Return a 2-D array with ones on the diagonal and zeros elsewhere
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
# to create any n-dimentional array
np.random.rand(5)

array([0.30388429, 0.05205684, 0.91382219, 0.88603065, 0.53878746])

In [21]:
np.random.rand(5,6)

array([[0.2549977 , 0.06298579, 0.28116706, 0.82470865, 0.13330778,
        0.08173344],
       [0.6677139 , 0.41812104, 0.47379148, 0.57024987, 0.68129274,
        0.24623773],
       [0.80501296, 0.57458911, 0.98853887, 0.25554688, 0.22184479,
        0.04182796],
       [0.1369841 , 0.82813632, 0.57252451, 0.84595882, 0.02452891,
        0.71097894],
       [0.32800897, 0.97607056, 0.67190517, 0.71386498, 0.0363838 ,
        0.10838743]])

In [22]:
#randn(d0, d1, ..., dn), Return a sample (or samples) from the "standard normal" distribution.
np.random.randn(8)


array([ 0.17980936,  0.31944564,  0.20555241,  0.96361221, -1.2304693 ,
        0.50093498,  1.7509677 ,  0.6301705 ])

In [23]:
np.random.randn(3,4)

array([[ 0.87410183, -0.78555725,  1.28710113,  0.18545982],
       [ 0.57693955, -0.91972651, -1.18165163,  1.01839036],
       [ 1.09527084, -0.03560246, -0.16798682, -0.70554401]])

In [26]:
#randint(low, high=None, size=None, dtype=int)
#Return random integers from `low` (inclusive) to `high` (exclusive).
np.random.randint(1,50,5)

array([22, 29, 49, 31, 31])

In [29]:
arr = np.arange(36)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [33]:
rnd = np.random.randint(0,50,20)

In [34]:
rnd

array([20, 37,  6, 14, 48,  0, 15, 24, 31, 32, 48,  7, 16, 24, 25,  5, 12,
       35, 11, 18])

In [35]:
arr.reshape(6,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [36]:
rnd.reshape(4,5)

array([[20, 37,  6, 14, 48],
       [ 0, 15, 24, 31, 32],
       [48,  7, 16, 24, 25],
       [ 5, 12, 35, 11, 18]])

In [39]:
rnd.max()

48

In [40]:
rnd.min()

0

In [42]:
arr.max()

35

In [43]:
arr.min()

0

In [44]:
rnd.argmax()

4

In [45]:
rnd.argmin()

5

In [46]:
rnd.shape

(20,)

In [47]:
rnd.reshape(4,5)

array([[20, 37,  6, 14, 48],
       [ 0, 15, 24, 31, 32],
       [48,  7, 16, 24, 25],
       [ 5, 12, 35, 11, 18]])

In [48]:
rnd.shape

(20,)

In [49]:
rnd = rnd.reshape(4,5)

In [50]:
rnd.shape

(4, 5)

In [53]:
from numpy.random import randint
randint(10,50)

49

In [55]:
arr = np.arange(0,20)

In [56]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [57]:
arr[14]

14

In [58]:
arr[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [59]:
arr[-1]

19

In [60]:
arr[:7]

array([0, 1, 2, 3, 4, 5, 6])

In [61]:
arr[10:]

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [68]:
slice_of_array = arr[0:10]

In [69]:
slice_of_array

array([132, 132, 132, 132, 132,   5,   6,   7,   8,   9])

In [72]:
src = slice_of_array[:5] = 187

In [73]:
slice_of_array

array([187, 187, 187, 187, 187,   5,   6,   7,   8,   9])

In [74]:
src

187

In [76]:
cpy = arr.copy()

In [77]:
cpy

array([187, 187, 187, 187, 187,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [78]:
arr

array([187, 187, 187, 187, 187,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [79]:
src = slice_of_array[:5] = 89

In [80]:
src

89

In [81]:
arr2d = np.array([[5,10,15],[3,9,45],[4,45,23]])
arr2d

array([[ 5, 10, 15],
       [ 3,  9, 45],
       [ 4, 45, 23]])

In [82]:
arr2d[2][1]

45

In [84]:
arr2d[2][2]

23

In [85]:
arr2d[:2,1:]

array([[10, 15],
       [ 9, 45]])

In [86]:
arr = np.arange(0,30)

In [87]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [90]:
yenta = arr > 5

In [91]:
yenta

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])